"""
Emoji data and search helpers for the on-screen keyboard.

EMOJI_DATA: list of (char, display_name, [keywords])
search(query, n)  — substring search on name + keywords → list of chars
suggest(word, n)  — exact/prefix keyword match for suggestion bar → list of chars
"""

EMOJI_DATA: list[tuple[str, str, list[str]]] = [
    # ── Smileys & Emotion ─────────────────────────────────────────────────────
    ("😀", "grinning face",              ["smile", "happy", "grin"]),
    ("😃", "grinning big eyes",          ["smile", "happy", "excited"]),
    ("😄", "grinning smiling eyes",      ["smile", "happy", "laugh"]),
    ("😁", "beaming face",               ["grin", "happy"]),
    ("😆", "laughing squinting",         ["laugh", "lol", "haha"]),
    ("😅", "sweat smile",                ["nervous", "phew", "sweat"]),
    ("🤣", "rolling on floor laughing",  ["rofl", "laugh", "lol", "funny"]),
    ("😂", "tears of joy",               ["laugh", "lol", "funny", "haha"]),
    ("🙂", "slightly smiling",           ["smile", "nice", "okay"]),
    ("🙃", "upside down face",           ["sarcasm", "irony", "silly"]),
    ("😉", "winking face",               ["wink", "flirt"]),
    ("😊", "smiling eyes",               ["happy", "smile", "blush"]),
    ("😇", "smiling halo",               ["angel", "innocent", "good"]),
    ("🥰", "smiling hearts",             ["love", "hearts", "crush", "adore"]),
    ("😍", "heart eyes",                 ["love", "heart", "crush", "wow"]),
    ("🤩", "star struck",                ["star", "wow", "amazing", "starstruck"]),
    ("😘", "blowing a kiss",             ["kiss", "love", "flirt", "mwah"]),
    ("😗", "kissing face",               ["kiss"]),
    ("😚", "kissing closed eyes",        ["kiss", "love"]),
    ("😙", "kissing smiling eyes",       ["kiss", "smile"]),
    ("🥲", "smiling with tear",          ["grateful", "relieved", "bittersweet"]),
    ("😋", "face savoring food",         ["yum", "delicious", "tasty", "food"]),
    ("😛", "face with tongue",           ["tongue", "playful", "silly"]),
    ("😜", "winking tongue",             ["tongue", "wink", "playful"]),
    ("🤪", "zany face",                  ["crazy", "silly", "wacky"]),
    ("😝", "squinting tongue",           ["tongue", "tease"]),
    ("🤑", "money mouth",                ["money", "rich", "cash"]),
    ("🤗", "hugging face",               ["hug", "happy", "warm"]),
    ("🤭", "hand over mouth",            ["oops", "secret", "giggle"]),
    ("🤫", "shushing face",              ["quiet", "shush", "secret"]),
    ("🤔", "thinking face",              ["think", "hmm", "ponder", "wondering"]),
    ("🤐", "zipper mouth",               ["silent", "secret", "quiet"]),
    ("🤨", "raised eyebrow",             ["suspicious", "doubt", "skeptical"]),
    ("😐", "neutral face",               ["neutral", "meh"]),
    ("😑", "expressionless face",        ["blank", "expressionless", "meh"]),
    ("😶", "face without mouth",         ["silent", "speechless", "no words"]),
    ("😏", "smirking face",              ["smirk", "smug", "flirt"]),
    ("😒", "unamused face",              ["unamused", "annoyed", "bored"]),
    ("🙄", "eye roll",                   ["eye roll", "whatever", "annoyed"]),
    ("😬", "grimacing face",             ["grimace", "awkward", "nervous"]),
    ("🤥", "lying face",                 ["lie", "pinocchio", "lying"]),
    ("😌", "relieved face",              ["relieved", "peaceful", "calm"]),
    ("😔", "pensive face",               ["sad", "pensive", "thoughtful"]),
    ("😪", "sleepy face",                ["sleepy", "tired", "drowsy"]),
    ("🤤", "drooling face",              ["drool", "hungry", "want"]),
    ("😴", "sleeping face",              ["sleep", "zzz", "tired", "night"]),
    ("😷", "medical mask",               ["sick", "mask", "ill", "covid"]),
    ("🤒", "thermometer face",           ["sick", "fever", "ill"]),
    ("🤕", "head bandage",               ["hurt", "injured", "ouch"]),
    ("🤢", "nauseated face",             ["sick", "nausea", "gross"]),
    ("🤮", "face vomiting",              ["vomit", "sick", "gross"]),
    ("🤧", "sneezing face",              ["sneeze", "cold", "sick"]),
    ("🥵", "hot face",                   ["hot", "heat", "sweating", "burning"]),
    ("🥶", "cold face",                  ["cold", "freezing", "frozen"]),
    ("🥴", "woozy face",                 ["dizzy", "drunk", "woozy"]),
    ("😵", "dizzy face",                 ["dizzy", "dead", "knocked out"]),
    ("🤯", "exploding head",             ["mind blown", "shocked", "explosion"]),
    ("🤠", "cowboy hat",                 ["cowboy", "western"]),
    ("🥳", "partying face",              ["party", "celebrate", "birthday"]),
    ("😎", "sunglasses face",            ["cool", "sunglasses", "awesome"]),
    ("🤓", "nerd face",                  ["nerd", "geek", "glasses"]),
    ("🧐", "face with monocle",          ["monocle", "curious", "investigate"]),
    ("😕", "confused face",              ["confused", "unsure", "puzzled"]),
    ("😟", "worried face",               ["worried", "concern"]),
    ("🙁", "slightly frowning",          ["sad", "frown"]),
    ("😮", "open mouth surprise",        ["surprised", "wow", "shocked"]),
    ("😯", "hushed face",                ["hushed", "surprised"]),
    ("😲", "astonished face",            ["astonished", "shocked", "surprised"]),
    ("😳", "flushed face",               ["flushed", "embarrassed", "blush"]),
    ("🥺", "pleading face",              ["pleading", "puppy eyes", "beg"]),
    ("😢", "crying face",                ["cry", "sad", "tear"]),
    ("😭", "loudly crying",              ["cry", "sob", "sad", "bawling"]),
    ("😱", "screaming in fear",          ["scream", "scared", "horror"]),
    ("😩", "weary face",                 ["tired", "weary", "exhausted"]),
    ("😫", "tired face",                 ["tired", "exhausted"]),
    ("🥱", "yawning face",               ["yawn", "tired", "bored"]),
    ("😤", "steam from nose",            ["frustrated", "angry", "triumph"]),
    ("😡", "pouting face",               ["angry", "mad", "rage"]),
    ("😠", "angry face",                 ["angry", "mad"]),
    ("🤬", "face symbols mouth",         ["angry", "swearing", "cursing"]),
    ("😈", "smiling devil",              ["devil", "evil", "mischief"]),
    ("👿", "angry devil",                ["devil", "evil", "demon"]),
    ("💀", "skull",                      ["skull", "dead", "death", "danger"]),
    ("☠️", "skull crossbones",           ["skull", "dead", "danger", "poison"]),
    ("💩", "pile of poo",                ["poop", "poo", "funny"]),
    ("🤡", "clown face",                 ["clown", "silly", "circus"]),
    ("👻", "ghost",                      ["ghost", "halloween", "spooky", "boo"]),
    ("👽", "alien",                      ["alien", "ufo", "space"]),
    ("🤖", "robot",                      ["robot", "ai", "machine", "bot"]),

    # ── People & Hands ───────────────────────────────────────────────────────
    ("👋", "waving hand",                ["wave", "hello", "hi", "bye"]),
    ("✋", "raised hand",                ["stop", "hand", "high five"]),
    ("🤚", "raised back hand",           ["hand", "stop"]),
    ("🖐️", "hand splayed",              ["hand", "five"]),
    ("🖖", "vulcan salute",              ["star trek", "spock"]),
    ("👌", "ok hand",                    ["ok", "perfect", "good", "okay"]),
    ("✌️", "victory hand",              ["peace", "victory", "two"]),
    ("🤞", "crossed fingers",            ["luck", "hope", "wish", "fingers crossed"]),
    ("🤟", "love you gesture",           ["love", "rock"]),
    ("🤘", "sign of horns",              ["rock", "metal", "horns"]),
    ("🤙", "call me hand",               ["call", "phone", "shaka"]),
    ("👈", "pointing left",              ["left", "point"]),
    ("👉", "pointing right",             ["right", "point"]),
    ("👆", "pointing up",                ["up", "point"]),
    ("👇", "pointing down",              ["down", "point"]),
    ("👍", "thumbs up",                  ["thumbs up", "like", "good", "yes", "approve"]),
    ("👎", "thumbs down",                ["thumbs down", "dislike", "bad", "no"]),
    ("✊", "raised fist",                ["fist", "power", "fight"]),
    ("👊", "oncoming fist",              ["punch", "fist", "fight"]),
    ("👏", "clapping hands",             ["clap", "applause", "good job", "bravo"]),
    ("🙌", "raising hands",              ["celebrate", "hands up", "praise"]),
    ("🤝", "handshake",                  ["handshake", "deal", "agreement"]),
    ("🙏", "folded hands",               ["pray", "please", "thanks", "hope", "namaste"]),
    ("💪", "flexed biceps",              ["muscle", "strong", "flex", "gym", "strength"]),
    ("👀", "eyes",                       ["eyes", "look", "see", "watch", "stare"]),
    ("👁️", "eye",                       ["eye", "see", "look"]),
    ("🧠", "brain",                      ["brain", "smart", "think", "mind"]),
    ("💅", "nail polish",                ["nails", "beauty", "manicure", "fabulous"]),

    # ── Animals ───────────────────────────────────────────────────────────────
    ("🐶", "dog face",                   ["dog", "puppy", "pet", "woof"]),
    ("🐱", "cat face",                   ["cat", "kitten", "pet", "meow"]),
    ("🐭", "mouse face",                 ["mouse", "rodent"]),
    ("🐹", "hamster",                    ["hamster", "pet", "cute"]),
    ("🐰", "rabbit face",                ["rabbit", "bunny", "cute"]),
    ("🦊", "fox",                        ["fox", "clever", "sly"]),
    ("🐻", "bear",                       ["bear", "animal"]),
    ("🐼", "panda",                      ["panda", "china", "cute"]),
    ("🐨", "koala",                      ["koala", "australia", "cute"]),
    ("🐯", "tiger face",                 ["tiger", "wild", "stripes"]),
    ("🦁", "lion",                       ["lion", "king", "wild", "roar"]),
    ("🐮", "cow face",                   ["cow", "moo", "farm"]),
    ("🐷", "pig face",                   ["pig", "oink", "farm"]),
    ("🐸", "frog",                       ["frog", "green"]),
    ("🐵", "monkey face",                ["monkey", "ape"]),
    ("🙈", "see no evil",                ["see no evil", "monkey"]),
    ("🙉", "hear no evil",               ["hear no evil", "monkey"]),
    ("🙊", "speak no evil",              ["speak no evil", "monkey"]),
    ("🐔", "chicken",                    ["chicken", "hen", "farm", "cluck"]),
    ("🐧", "penguin",                    ["penguin", "cold", "bird"]),
    ("🦆", "duck",                       ["duck", "quack", "bird"]),
    ("🦉", "owl",                        ["owl", "wise", "night"]),
    ("🦇", "bat",                        ["bat", "halloween", "vampire"]),
    ("🐺", "wolf",                       ["wolf", "howl", "wild"]),
    ("🐴", "horse face",                 ["horse", "pony"]),
    ("🦄", "unicorn",                    ["unicorn", "magic", "fantasy"]),
    ("🐝", "bee",                        ["bee", "honey", "insect", "buzz"]),
    ("🦋", "butterfly",                  ["butterfly", "beautiful", "transform"]),
    ("🐛", "bug",                        ["bug", "caterpillar", "insect"]),
    ("🐞", "ladybug",                    ["ladybug", "bug", "luck"]),
    ("🕷️", "spider",                    ["spider", "scary", "web"]),
    ("🐢", "turtle",                     ["turtle", "slow", "shell"]),
    ("🐍", "snake",                      ["snake", "reptile", "danger"]),
    ("🦖", "t-rex",                      ["dinosaur", "trex", "prehistoric"]),
    ("🐙", "octopus",                    ["octopus", "sea", "tentacles"]),
    ("🦑", "squid",                      ["squid", "sea"]),
    ("🦈", "shark",                      ["shark", "danger", "sea"]),
    ("🐬", "dolphin",                    ["dolphin", "smart", "sea", "porpoise"]),
    ("🐳", "spouting whale",             ["whale", "sea", "big"]),
    ("🐟", "fish",                       ["fish", "sea", "swimming"]),
    ("🦄", "unicorn",                    ["unicorn", "magic"]),
    ("🦓", "zebra",                      ["zebra", "stripes", "africa"]),
    ("🐘", "elephant",                   ["elephant", "big", "trunk"]),
    ("🦒", "giraffe",                    ["giraffe", "tall", "africa"]),
    ("🦘", "kangaroo",                   ["kangaroo", "australia", "jump"]),
    ("🐕", "dog",                        ["dog", "pet"]),
    ("🐈", "cat",                        ["cat", "pet"]),
    ("🐾", "paw prints",                 ["paw", "animal", "pet", "dog", "cat"]),
    ("🌸", "cherry blossom",             ["cherry blossom", "japan", "spring", "flower"]),
    ("🌹", "rose",                       ["rose", "flower", "love", "red"]),
    ("🌻", "sunflower",                  ["sunflower", "yellow", "sun"]),
    ("🍀", "four leaf clover",           ["luck", "clover", "lucky"]),
    ("🌵", "cactus",                     ["cactus", "desert", "spiky"]),
    ("🌴", "palm tree",                  ["palm", "tropical", "beach"]),
    ("🌲", "tree",                       ["tree", "forest", "nature", "pine"]),
    ("🌺", "hibiscus",                   ["hibiscus", "flower", "tropical"]),
    ("🍄", "mushroom",                   ["mushroom", "fungus", "mario"]),
    ("🌈", "rainbow",                    ["rainbow", "colorful", "hope", "pride"]),
    ("❄️", "snowflake",                 ["snow", "cold", "winter", "ice"]),
    ("🔥", "fire",                       ["fire", "hot", "flame", "lit", "burn"]),
    ("💧", "droplet",                    ["water", "drop", "rain"]),
    ("🌊", "water wave",                 ["wave", "ocean", "sea", "surf"]),
    ("⚡", "lightning",                  ["lightning", "electric", "fast", "energy"]),
    ("🌙", "crescent moon",              ["moon", "night", "sleep"]),
    ("☀️", "sun",                        ["sun", "sunny", "bright", "warm"]),
    ("⭐", "star",                       ["star", "favourite", "rating"]),
    ("✨", "sparkles",                   ["sparkle", "shine", "magic", "glitter"]),
    ("🌍", "earth",                      ["earth", "world", "globe", "planet"]),
    ("🌏", "earth asia",                 ["earth", "world", "asia", "globe"]),

    # ── Food & Drink ──────────────────────────────────────────────────────────
    ("🍎", "red apple",                  ["apple", "fruit", "red"]),
    ("🍋", "lemon",                      ["lemon", "sour", "yellow"]),
    ("🍇", "grapes",                     ["grapes", "fruit", "wine"]),
    ("🍓", "strawberry",                 ["strawberry", "fruit", "red"]),
    ("🍒", "cherries",                   ["cherry", "fruit", "red"]),
    ("🍑", "peach",                      ["peach", "fruit"]),
    ("🥝", "kiwi",                       ["kiwi", "fruit", "green"]),
    ("🥑", "avocado",                    ["avocado", "guac", "healthy"]),
    ("🍆", "eggplant",                   ["eggplant", "aubergine", "vegetable"]),
    ("🥕", "carrot",                     ["carrot", "vegetable", "orange"]),
    ("🌽", "corn",                       ["corn", "vegetable"]),
    ("🌶️", "hot pepper",                ["pepper", "spicy", "hot", "chili"]),
    ("🍞", "bread",                      ["bread", "bake", "toast"]),
    ("🧀", "cheese",                     ["cheese", "dairy"]),
    ("🥚", "egg",                        ["egg", "breakfast"]),
    ("🍳", "frying pan",                 ["cook", "egg", "breakfast", "frying"]),
    ("🥓", "bacon",                      ["bacon", "breakfast", "meat"]),
    ("🍔", "hamburger",                  ["burger", "hamburger", "fast food"]),
    ("🍟", "french fries",               ["fries", "fast food", "chips"]),
    ("🍕", "pizza",                      ["pizza", "italian", "food"]),
    ("🌮", "taco",                       ["taco", "mexican", "food"]),
    ("🌯", "burrito",                    ["burrito", "mexican", "wrap"]),
    ("🍜", "noodles ramen",              ["noodles", "ramen", "asian", "soup"]),
    ("🍝", "spaghetti",                  ["pasta", "spaghetti", "italian"]),
    ("🍣", "sushi",                      ["sushi", "japanese", "fish"]),
    ("🍱", "bento",                      ["bento", "japanese", "lunch"]),
    ("🍩", "doughnut",                   ["donut", "doughnut", "sweet"]),
    ("🍪", "cookie",                     ["cookie", "sweet", "chocolate chip"]),
    ("🎂", "birthday cake",              ["birthday", "cake", "celebration"]),
    ("🍰", "cake",                       ["cake", "sweet", "dessert"]),
    ("🧁", "cupcake",                    ["cupcake", "sweet", "birthday"]),
    ("🍫", "chocolate",                  ["chocolate", "sweet", "candy"]),
    ("🍬", "candy",                      ["candy", "sweet", "sugar"]),
    ("🍭", "lollipop",                   ["lollipop", "candy", "sweet"]),
    ("🍦", "ice cream cone",             ["ice cream", "cone", "sweet", "cold"]),
    ("🍨", "ice cream",                  ["ice cream", "sweet", "cold"]),
    ("🍿", "popcorn",                    ["popcorn", "movie", "cinema", "snack"]),
    ("☕", "coffee",                     ["coffee", "tea", "hot", "cafe"]),
    ("🍵", "tea",                        ["tea", "green tea", "hot drink"]),
    ("🧋", "bubble tea",                 ["boba", "tea", "milk tea", "bubble"]),
    ("🍺", "beer",                       ["beer", "drink", "alcohol", "cheers"]),
    ("🍻", "clinking beers",             ["beer", "cheers", "drink", "toast"]),
    ("🥂", "champagne glasses",          ["champagne", "toast", "celebrate"]),
    ("🍷", "wine",                       ["wine", "drink", "alcohol", "red"]),
    ("🍸", "cocktail",                   ["cocktail", "drink", "martini"]),
    ("🍹", "tropical drink",             ["cocktail", "tropical", "drink"]),
    ("🧃", "juice box",                  ["juice", "drink", "box"]),
    ("🥤", "cup with straw",             ["drink", "soda", "juice", "smoothie"]),
    ("💧", "water",                      ["water", "drink", "drop", "hydrate"]),
    ("🍯", "honey pot",                  ["honey", "bee", "sweet"]),

    # ── Travel & Places ───────────────────────────────────────────────────────
    ("🚗", "car",                        ["car", "drive", "vehicle", "road"]),
    ("🚕", "taxi",                       ["taxi", "cab", "car"]),
    ("🚌", "bus",                        ["bus", "transport", "school"]),
    ("🏎️", "racing car",               ["race", "car", "fast", "formula"]),
    ("🚓", "police car",                 ["police", "cop", "car"]),
    ("🚑", "ambulance",                  ["ambulance", "emergency", "hospital"]),
    ("🚒", "fire engine",                ["fire", "truck", "emergency"]),
    ("🚚", "truck",                      ["delivery", "truck", "shipping"]),
    ("🚲", "bicycle",                    ["bike", "bicycle", "ride", "cycle"]),
    ("🛴", "scooter",                    ["scooter", "ride"]),
    ("✈️", "airplane",                  ["plane", "airplane", "fly", "travel", "flight"]),
    ("🚀", "rocket",                     ["rocket", "space", "launch", "fast"]),
    ("🛸", "flying saucer",              ["ufo", "alien", "space"]),
    ("🚢", "ship",                       ["ship", "boat", "cruise", "sailing"]),
    ("⛵", "sailboat",                   ["sailboat", "boat", "sailing"]),
    ("🚁", "helicopter",                 ["helicopter", "fly", "chopper"]),
    ("🏖️", "beach",                     ["beach", "vacation", "summer", "sun"]),
    ("🏔️", "mountain",                  ["mountain", "nature", "climb", "hike"]),
    ("🏝️", "island",                    ["island", "tropical", "deserted"]),
    ("🏕️", "camping",                   ["camping", "tent", "outdoor", "forest"]),
    ("🗺️", "map",                        ["map", "world", "travel", "navigate"]),
    ("🏠", "house",                      ["home", "house", "building"]),
    ("🏢", "office",                     ["office", "work", "building", "city"]),
    ("🏥", "hospital",                   ["hospital", "medical", "health", "doctor"]),
    ("🏦", "bank",                       ["bank", "money", "finance"]),
    ("🏨", "hotel",                      ["hotel", "travel", "stay", "holiday"]),
    ("🕌", "mosque",                     ["mosque", "islam", "religion"]),
    ("⛪", "church",                     ["church", "religion", "cross", "pray"]),
    ("🌃", "night city",                 ["night", "city", "stars", "dark"]),
    ("🌆", "city sunset",                ["sunset", "city", "dusk"]),

    # ── Activities & Sports ───────────────────────────────────────────────────
    ("⚽", "soccer ball",                ["soccer", "football", "ball", "sport"]),
    ("🏀", "basketball",                 ["basketball", "sport", "ball"]),
    ("🏈", "american football",          ["football", "american", "sport"]),
    ("⚾", "baseball",                   ["baseball", "sport", "ball"]),
    ("🎾", "tennis",                     ["tennis", "sport", "ball"]),
    ("🏐", "volleyball",                 ["volleyball", "sport", "ball"]),
    ("🎱", "pool 8 ball",                ["billiards", "pool", "8 ball", "snooker"]),
    ("🏓", "ping pong",                  ["ping pong", "table tennis", "sport"]),
    ("🏸", "badminton",                  ["badminton", "sport"]),
    ("🥊", "boxing glove",               ["boxing", "fight", "sport", "gym"]),
    ("🎿", "skis",                       ["ski", "skiing", "winter", "snow"]),
    ("⛷️", "skier",                     ["ski", "skiing", "winter", "slope"]),
    ("🏊", "swimming",                   ["swim", "swimming", "pool", "water"]),
    ("🏋️", "weightlifting",             ["gym", "weights", "fitness", "workout"]),
    ("🧘", "yoga",                       ["yoga", "meditate", "relax", "zen"]),
    ("🏆", "trophy",                     ["trophy", "win", "award", "winner", "champion"]),
    ("🥇", "gold medal",                 ["gold", "win", "first", "medal", "best"]),
    ("🥈", "silver medal",               ["silver", "second", "medal"]),
    ("🥉", "bronze medal",               ["bronze", "third", "medal"]),
    ("🎯", "bullseye",                   ["target", "darts", "goal", "aim", "perfect"]),
    ("🎳", "bowling",                    ["bowling", "ball", "sport", "strike"]),
    ("🎮", "video game",                 ["game", "controller", "gaming", "play"]),
    ("🕹️", "joystick",                  ["joystick", "game", "arcade"]),
    ("🎲", "dice",                       ["dice", "game", "random", "roll", "board game"]),
    ("♟️", "chess",                     ["chess", "strategy", "game"]),
    ("🎭", "theatre",                    ["theater", "theatre", "drama", "masks"]),
    ("🎨", "art palette",                ["art", "paint", "creative", "palette", "draw"]),
    ("🎬", "movie clapperboard",         ["movie", "film", "cinema", "action"]),
    ("🎤", "microphone",                 ["microphone", "sing", "music", "mic"]),
    ("🎧", "headphones",                 ["headphones", "music", "listen", "audio"]),
    ("🎵", "music note",                 ["music", "note", "song"]),
    ("🎶", "music notes",                ["music", "notes", "song", "melody"]),
    ("🎸", "guitar",                     ["guitar", "music", "rock", "band"]),
    ("🎹", "piano",                      ["piano", "keyboard", "music", "keys"]),
    ("🥁", "drum",                       ["drum", "music", "beat", "percussion"]),
    ("🎻", "violin",                     ["violin", "music", "classical"]),
    ("🎺", "trumpet",                    ["trumpet", "music", "brass", "jazz"]),
    ("🎷", "saxophone",                  ["saxophone", "sax", "jazz", "music"]),

    # ── Objects ───────────────────────────────────────────────────────────────
    ("📱", "mobile phone",               ["phone", "mobile", "cell", "smartphone"]),
    ("💻", "laptop",                     ["laptop", "computer", "work", "coding"]),
    ("🖥️", "desktop computer",          ["computer", "desktop", "monitor", "pc"]),
    ("⌨️", "keyboard",                  ["keyboard", "type", "computer", "keys"]),
    ("🖱️", "mouse",                     ["mouse", "computer", "click"]),
    ("💾", "floppy disk",                ["floppy", "disk", "save"]),
    ("📷", "camera",                     ["camera", "photo", "picture", "selfie"]),
    ("📹", "video camera",               ["video", "camera", "record", "film"]),
    ("📺", "television",                 ["tv", "television", "watch", "screen"]),
    ("📻", "radio",                      ["radio", "music", "broadcast"]),
    ("⌚", "watch",                      ["watch", "time", "wristwatch", "clock"]),
    ("⏰", "alarm clock",                ["alarm", "clock", "wake up", "morning"]),
    ("📡", "satellite",                  ["satellite", "antenna", "signal", "wifi"]),
    ("🔋", "battery",                    ["battery", "power", "charge", "energy"]),
    ("💡", "light bulb",                 ["idea", "light", "bulb", "bright", "tip"]),
    ("🔦", "flashlight",                 ["flashlight", "torch", "light"]),
    ("🕯️", "candle",                    ["candle", "light", "flame", "romantic"]),
    ("💰", "money bag",                  ["money", "bag", "rich", "cash", "dollar"]),
    ("💵", "dollar",                     ["dollar", "money", "cash", "usd"]),
    ("💳", "credit card",                ["credit card", "payment", "card", "bank"]),
    ("💎", "diamond",                    ["diamond", "gem", "jewel", "precious", "ring"]),
    ("🔧", "wrench",                     ["wrench", "tool", "fix", "repair"]),
    ("🔨", "hammer",                     ["hammer", "tool", "build", "hit"]),
    ("🪛", "screwdriver",                ["screwdriver", "tool", "fix"]),
    ("🔑", "key",                        ["key", "unlock", "access", "lock"]),
    ("🔒", "locked",                     ["lock", "secure", "locked", "private"]),
    ("🔓", "unlocked",                   ["unlock", "open", "access"]),
    ("🧲", "magnet",                     ["magnet", "attract", "magnetic"]),
    ("🧪", "test tube",                  ["test tube", "science", "experiment", "lab"]),
    ("🧬", "dna",                        ["dna", "genetics", "science", "biology"]),
    ("🔭", "telescope",                  ["telescope", "space", "stars", "astronomy"]),
    ("🔬", "microscope",                 ["microscope", "science", "biology", "lab"]),
    ("🩺", "stethoscope",                ["stethoscope", "doctor", "medical", "health"]),
    ("💊", "pill",                       ["pill", "medicine", "drug", "health"]),
    ("🩹", "bandage",                    ["bandage", "hurt", "wound", "plaster"]),
    ("🛒", "shopping cart",              ["cart", "shopping", "grocery", "basket"]),
    ("🎁", "gift",                       ["gift", "present", "birthday", "surprise"]),
    ("🎀", "ribbon",                     ["ribbon", "bow", "gift", "pink"]),
    ("🎊", "confetti",                   ["confetti", "party", "celebrate", "fun"]),
    ("🎉", "party popper",               ["party", "celebrate", "confetti", "birthday"]),
    ("🎈", "balloon",                    ["balloon", "party", "birthday", "float"]),
    ("🧸", "teddy bear",                 ["teddy", "bear", "toy", "cute"]),
    ("📚", "books",                      ["books", "read", "library", "study", "education"]),
    ("📖", "open book",                  ["book", "read", "open", "story"]),
    ("✏️", "pencil",                    ["pencil", "write", "draw", "edit"]),
    ("📝", "memo",                       ["memo", "write", "note", "pencil"]),
    ("📌", "pushpin",                    ["pin", "location", "mark", "saved"]),
    ("🔖", "bookmark",                   ["bookmark", "save", "book", "mark"]),
    ("📎", "paperclip",                  ["paperclip", "attach", "clip", "link"]),
    ("✂️", "scissors",                  ["scissors", "cut", "craft", "trim"]),
    ("🗑️", "trash",                     ["trash", "delete", "waste", "bin"]),
    ("🏠", "home",                       ["home", "house", "live"]),
    ("🚪", "door",                       ["door", "entrance", "exit", "open"]),
    ("🪞", "mirror",                     ["mirror", "reflection", "vanity"]),
    ("🛋️", "couch",                     ["couch", "sofa", "living room", "relax"]),
    ("🛁", "bathtub",                    ["bath", "bathtub", "soak", "relax"]),
    ("🧹", "broom",                      ["broom", "sweep", "clean", "witch"]),
    ("🧴", "lotion",                     ["lotion", "cream", "skincare"]),
    ("🧼", "soap",                       ["soap", "wash", "clean", "hygiene"]),

    # ── Symbols ───────────────────────────────────────────────────────────────
    ("❤️", "red heart",                 ["heart", "love", "red", "romance"]),
    ("🧡", "orange heart",               ["heart", "orange", "love"]),
    ("💛", "yellow heart",               ["heart", "yellow", "love", "friends"]),
    ("💚", "green heart",                ["heart", "green", "love", "nature"]),
    ("💙", "blue heart",                 ["heart", "blue", "love"]),
    ("💜", "purple heart",               ["heart", "purple", "love"]),
    ("🖤", "black heart",                ["heart", "black", "dark"]),
    ("🤍", "white heart",                ["heart", "white", "pure"]),
    ("💔", "broken heart",               ["broken heart", "heartbreak", "sad", "breakup"]),
    ("💕", "two hearts",                 ["hearts", "love", "romance"]),
    ("💖", "sparkling heart",            ["heart", "sparkle", "love"]),
    ("💗", "growing heart",              ["heart", "love", "grow"]),
    ("💘", "heart arrow",                ["heart", "cupid", "love", "arrow"]),
    ("✅", "check mark",                 ["check", "yes", "done", "correct", "tick", "okay"]),
    ("❌", "cross mark",                 ["cross", "no", "wrong", "x", "cancel", "delete"]),
    ("⚠️", "warning",                   ["warning", "caution", "alert", "danger"]),
    ("🚫", "prohibited",                 ["no", "prohibited", "forbidden", "banned"]),
    ("❗", "exclamation",                ["exclamation", "warning", "important", "alert"]),
    ("❓", "question mark",              ["question", "ask", "confused", "help"]),
    ("💯", "hundred points",             ["100", "perfect", "score", "hundred", "all"]),
    ("🔝", "top",                        ["top", "up", "back to top"]),
    ("🔔", "bell",                       ["bell", "notification", "ring", "alert"]),
    ("🔕", "mute bell",                  ["mute", "silent", "no sound", "quiet"]),
    ("📣", "megaphone",                  ["megaphone", "announce", "loud", "shout"]),
    ("💬", "speech bubble",              ["chat", "speech", "message", "talk", "comment"]),
    ("💭", "thought bubble",             ["thought", "thinking", "think", "dream"]),
    ("♻️", "recycle",                   ["recycle", "green", "eco", "environment"]),
    ("🔮", "crystal ball",               ["crystal ball", "magic", "future", "predict"]),
    ("🎆", "fireworks",                  ["fireworks", "celebrate", "new year"]),
    ("🎇", "sparkler",                   ["sparkler", "celebrate", "fireworks"]),
    ("💥", "explosion",                  ["explosion", "crash", "boom", "bang"]),
    ("💫", "dizzy stars",                ["dizzy", "stars", "spin"]),
    ("💢", "anger symbol",               ["anger", "angry", "mad", "rage"]),
    ("💤", "zzz sleep",                  ["sleep", "zzz", "tired", "boring"]),
    ("💨", "dash wind",                  ["fast", "wind", "run", "dash", "speed"]),
    ("💦", "sweat droplets",             ["sweat", "water", "wet", "drops"]),
    ("🔴", "red circle",                 ["red", "circle", "stop"]),
    ("🟠", "orange circle",              ["orange", "circle"]),
    ("🟡", "yellow circle",              ["yellow", "circle"]),
    ("🟢", "green circle",               ["green", "circle", "go", "online"]),
    ("🔵", "blue circle",                ["blue", "circle"]),
    ("⚫", "black circle",               ["black", "circle", "dark"]),
    ("⚪", "white circle",               ["white", "circle"]),
    ("☮️", "peace symbol",              ["peace", "symbol", "hippie"]),
    ("♾️", "infinity",                  ["infinity", "forever", "loop", "endless"]),
    ("🌐", "globe",                      ["globe", "internet", "world", "web", "online"]),

    # ── Flags ─────────────────────────────────────────────────────────────────
    ("🚩", "red flag",                   ["flag", "red flag", "warning", "marker"]),
    ("🏳️", "white flag",               ["white flag", "surrender", "peace"]),
    ("🏴‍☠️", "pirate flag",           ["pirate", "skull", "jolly roger"]),
    ("🇬🇧", "uk flag",                 ["uk", "britain", "england", "flag"]),
    ("🇺🇸", "usa flag",                ["usa", "america", "us", "flag", "american"]),
    ("🇦🇺", "australia flag",          ["australia", "flag", "aussie"]),
    ("🇨🇦", "canada flag",             ["canada", "flag", "canadian"]),
    ("🇩🇪", "germany flag",            ["germany", "german", "flag"]),
    ("🇫🇷", "france flag",             ["france", "french", "flag"]),
    ("🇯🇵", "japan flag",              ["japan", "japanese", "flag"]),
    ("🇨🇳", "china flag",              ["china", "chinese", "flag"]),
    ("🇧🇷", "brazil flag",             ["brazil", "flag"]),
    ("🇮🇳", "india flag",              ["india", "flag", "indian"]),
    ("🇪🇸", "spain flag",              ["spain", "spanish", "flag"]),
    ("🇮🇹", "italy flag",              ["italy", "italian", "flag"]),
    ("🇲🇽", "mexico flag",             ["mexico", "flag", "mexican"]),
]

# Build reverse lookup once at import time
_LOOKUP: dict[str, tuple[str, list[str]]] = {
    char: (name, kws) for char, name, kws in EMOJI_DATA
}


def search(query: str, n: int = 60) -> list[str]:
    """Return up to n emoji chars whose name or keywords contain query."""
    if not query:
        return [e[0] for e in EMOJI_DATA[:n]]
    q = query.lower().strip()
    if not q:
        return [e[0] for e in EMOJI_DATA[:n]]
    results: list[str] = []
    for char, name, keywords in EMOJI_DATA:
        if q in name or any(q in kw for kw in keywords):
            results.append(char)
            if len(results) >= n:
                break
    return results


def suggest(word: str, n: int = 3) -> list[str]:
    """
    Return up to n emojis for the suggestion bar, ranked by match quality.

    Ranking (best first):
      1. Exact keyword match (remaining chars = 0)
      2. Name of the emoji starts with word (more "on-topic")
      3. Fewer remaining characters in the matched keyword
      4. Original EMOJI_DATA order as tiebreaker
    """
    w = word.lower().strip()
    if len(w) < 2:
        return []

    scored: list[tuple[int, int, int, str]] = []  # (exact, name_bonus, remaining, char)
    for idx, (char, name, keywords) in enumerate(EMOJI_DATA):
        best_remaining = None
        for kw in keywords:
            if w == kw:
                best_remaining = 0
                break
            if len(w) >= 3 and kw.startswith(w):
                rem = len(kw) - len(w)
                if best_remaining is None or rem < best_remaining:
                    best_remaining = rem
        if best_remaining is None:
            continue
        exact      = 0 if best_remaining == 0 else 1   # lower = better
        name_bonus = 0 if name.startswith(w) else 1    # lower = better
        scored.append((exact, name_bonus, best_remaining, char))

    scored.sort(key=lambda t: (t[0], t[1], t[2]))
    return [char for _, _, _, char in scored[:n]]
